### ISSUE TITLE
Aiuto

### ISSUE THREAD

**Issue by veronicasolinas** [veronicasolinas/veronicasolinas.github.io#4]
@grammaton possiamo riguardare come si crea un'altra pagina e quindi un collegamento?
Grazie

**Comment by grammaton** [comment]
@veronicasolinas ho fatto una pagina di prova, puoi leggere dalla pull request #5 come l'ho integrata oppure accettare la pull request ed integrare il codice direttamente nel tuo e poi replicare per altre pagine. 

G

**Comment by grammaton** [comment]
@veronicasolinas se fai merge pull request ricordati di chiudere questa issue.
