### ISSUE TITLE
AIUTO

### ISSUE THREAD

**Issue by veronicasolinas** [veronicasolinas/veronicasolinas.github.io#6]
@grammaton 
Ho rotto tutte le pagine create come avevamo detto, perchè quando carico la foto sulla nuova pagina creata, non solo non si carica la foto, ma cambiano tutte le posizioni delle scritte.
Grazie in anticipo per l'aiuto.

**Comment by grammaton** [comment]
ciao,
ti ho appena inviato una pull request #7  con le modifiche

g
